// 多語言翻譯數據
const translations = {
    'zh-TW': {
        // 頁面標題和品牌
        'page.title': '村齊超音波 - 專業超音波清洗機設備',
        'brand.name': '村齊超音波',
        
        // 導航
        'nav.home': '首頁',
        'nav.about': '關於',
        'nav.technology': '技術',
        'nav.products': '產品應用',
        'nav.solutions': '解決方案',
        'nav.contact': '聯絡',
        
        // Hero 區域
        'hero.badge': '15年專業客製化經驗',
        'hero.title': '客製化超音波清洗',
        'hero.subtitle': '為您量身打造清洗解決方案',
        'hero.description': '根據您的工件特性、清洗需求與產線配置，設計專屬的超音波清洗設備',
        'hero.feature1': '量身定製',
        'hero.feature2': '專業測試',
        'hero.feature3': '完整服務',
        'hero.explore': '探索產品',
        'hero.consult': '免費需求評估',
        'hero.process': '了解設計流程',
        'hero.clients': '合作客戶',
        'hero.experience': '年專業經驗',
        'hero.cases': '成功案例',
        
        // 設計流程
        'process.label': '設計流程',
        'process.title': '專業客製化設計流程',
        'process.subtitle': '從需求分析到交付使用，我們提供完整的客製化設計服務',
        'process.step1.title': '需求諮詢',
        'process.step1.desc': '深入了解您的工件材質、污染類型、清洗要求及產線配置',
        'process.step1.item1': '現場勘查評估',
        'process.step1.item2': '清洗需求分析',
        'process.step1.item3': '技術可行性討論',
        'process.step2.title': '樣品測試',
        'process.step2.desc': '使用實際工件進行清洗測試，確認最佳參數設定',
        'process.step2.item1': '免費樣品測試',
        'process.step2.item2': '多種頻率驗證',
        'process.step2.item3': '清洗效果確認',
        'process.step3.title': '方案設計',
        'process.step3.desc': '根據測試結果設計專屬設備，包含機械結構與控制系統',
        'process.step3.item1': '3D設計圖面',
        'process.step3.item2': '詳細規格說明',
        'process.step3.item3': '報價與交期評估',
        'process.step4.title': '製造組裝',
        'process.step4.desc': '採用高品質零組件，嚴格品質控制下完成設備製造',
        'process.step4.item1': '精密機械加工',
        'process.step4.item2': '電控系統整合',
        'process.step4.item3': '出廠測試驗證',
        'process.step5.title': '安裝調試',
        'process.step5.desc': '專業工程師到場安裝，完成設備調試與人員教育訓練',
        'process.step5.item1': '現場安裝調試',
        'process.step5.item2': '操作教育訓練',
        'process.step5.item3': '驗收測試確認',
        'process.cta.title': '準備開始您的客製化項目？',
        'process.cta.desc': '聯繫我們的工程團隊，獲得專業的需求評估與解決方案',
        'process.cta.button': '開始需求評估',
        
        // 首頁介紹區塊
        'intro.title': '專業超音波清洗技術領導者',
        'intro.description': '村齊超音波成立於2009年，專注於客製化超音波清洗設備的研發與製造。我們深耕超音波清洗技術領域15年，為各行各業提供量身打造的清洗解決方案。',
        
        // 關於我們
        'about.label': '關於我們',
        'about.title': '創新驅動未來',
        'about.subtitle': '專業超音波清洗設備領導者',
        'about.description': '村齊超音波致力於提供最先進的超音波清洗技術，我們的清洗設備涵蓋各個產業領域，從精密電子到醫療器械，為客戶提供高效潔淨的清洗解決方案。',
        'about.innovation': '創新技術',
        'about.innovation.desc': '持續研發突破性技術',
        'about.quality': '品質保證',
        'about.quality.desc': '國際認證品質管理',
        'about.precision': '精密控制',
        'about.eco': '環保節能',
        'about.efficiency': '高效生產',
        
        // 技術展示
        'tech.label': '技術能力',
        'tech.title': '多元化客製技術方案',
        'tech.subtitle': '針對不同應用需求，我們具備完整的技術解決方案',
        'tech.custom.title': '頻率客製化',
        'tech.custom.desc': '根據工件特性選擇最適頻率',
        'tech.custom.freq1': '20kHz 大功率清洗',
        'tech.custom.freq2': '40kHz 精密清洗',
        'tech.custom.freq3': '80kHz 超精密清洗',
        'tech.custom.freq4': '多頻同步作業',
        'tech.solution.title': '清洗液客製化',
        'tech.solution.desc': '配合不同材質設計專用清洗配方',
        'tech.solution.water': '純水清洗系統',
        'tech.solution.solvent': '有機溶劑系統',
        'tech.solution.alkaline': '鹼性清洗系統',
        'tech.solution.acid': '酸性清洗系統',
        'tech.control.title': '控制系統客製化',
        'tech.control.desc': '智能化控制滿足自動化需求',
        'tech.control.plc': 'PLC控制系統',
        'tech.control.hmi': '人機介面設計',
        'tech.control.auto': '全自動化整合',
        'tech.control.remote': '遠端監控功能',
        'tech.structure.title': '機械結構客製化',
        'tech.structure.desc': '針對產線配置設計專屬結構',
        'tech.structure.single': '單槽式設計',
        'tech.structure.multi': '多槽連續式',
        'tech.structure.conveyor': '輸送帶整合',
        'tech.structure.robot': '機械手臂配合',
        
        // 產品展示
        'products.label': '產品系列',
        'products.title': '專業設備解決方案',
        'products.smart.title': '智能型超音波清洗機',
        'products.smart.desc': '搭載AI控制系統的新一代清洗設備，適用於各種精密零件清洗',
        'products.precision.title': '精密電子清洗系統',
        'products.precision.desc': '專為電子元件設計的精密清洗方案，有效去除助焊劑、油污等污染',
        'products.auto.title': '全自動化清洗線',
        'products.auto.desc': '整合機器人的自動化清洗解決方案，適合大量生產環境',
        'products.badge.hot': '熱銷',
        'products.badge.new': '新品',
        'products.tag.smart': '智能控制',
        'products.tag.efficient': '高效清洗',
        'products.tag.eco': '節能環保',
        'products.tag.precision': '精密清洗',
        'products.tag.safe': '無損傷',
        'products.tag.fast': '高效率',
        'products.tag.auto': '全自動',
        'products.tag.capacity': '高產能',
        'products.tag.iot': '智能監控',
        
        // 解決方案
        'solutions.label': '應用領域',
        'solutions.title': '全方位清洗解決方案',
        'solutions.auto.title': '汽車產業',
        'solutions.auto.desc': '引擎零件、車燈、感測器等精密清洗，去除油污、金屬屑屑',
        'solutions.medical.title': '醫療器械',
        'solutions.medical.desc': '醫療器械、手術器具的精密清洗，達到無菌標準',
        'solutions.electronic.title': '電子產業',
        'solutions.electronic.desc': 'PCB電路板、電子元件的助焊劑清洗，提升產品品質',
        'solutions.optical.title': '光學產業',
        'solutions.optical.desc': '鏡頭、光學元件的精密清洗，保持光學品質',
        'solutions.learn': '深入了解',
        
        // 客戶案例
        'cases.label': '客戶見證',
        'cases.title': '真實案例 · 可信賴的清洗效果',
        'cases.before': '清洗前',
        'cases.after': '清洗後',
        'cases.dirty': '髒污嚴重',
        'cases.clean': '潔淨如新',
        'cases.oil': '油污殘留',
        'cases.complete': '完全清潔',
        'cases.oxidation': '表面氧化',
        'cases.bright': '光亮如新',
        'cases.electronic.title': '精密電子元件清洗',
        'cases.electronic.desc': '某知名電子廠PCB板清洗案例，清洗效率提升300%，良品率達99.8%',
        'cases.auto.title': '汽車零件清洗',
        'cases.auto.desc': '汽車引擎零件深度清洗，有效去除碳積和油污，延長使用壽命',
        'cases.optical.title': '光學鏡頭清洗',
        'cases.optical.desc': '精密光學鏡頭清洗，無損傷清除表面污染，保持光學性能',
        'cases.time': '清洗時間',
        'cases.rate': '良品率',
        'cases.cleanliness': '清潔度',
        'cases.damage': '無損率',
        'cases.testimonial1': '"村齊的超音波清洗機幫我們解決了精密零件清洗的難題，效率提升了3倍！"',
        'cases.author1': '張總經理',
        'cases.company1': '精密科技股份有限公司',
        'cases.testimonial2': '"清洗效果令人驚艷，完全沒有化學殘留，是我們醫療器械清洗的最佳選擇。"',
        'cases.author2': '李院長',
        'cases.company2': '台北醫學中心',
        
        // CTA 號召行動
        'cta.title': '準備好提升您的清洗效率了嗎？',
        'cta.description': '立即聯繫我們，獲得專屬的超音波清洗解決方案',
        'cta.contact': '立即諮詢',
        'cta.phone': '02-1234-5678',
        
        // 聯絡我們
        'contact.label': '聯絡我們',
        'contact.title': '隨時為您服務',
        'contact.address': '總部地址',
        'contact.address.value': '台北市信義區信義路五段7號',
        'contact.phone': '聯絡電話',
        'contact.phone.value': '02-1234-5678',
        'contact.email': '電子郵件',
        'contact.email.value': 'info@cunqi-ultrasonic.com.tw',
        'contact.hours': '營業時間',
        'contact.hours.value': '週一至週五 9:00-18:00',
        'contact.form.title': '線上諮詢表單',
        'contact.form.name': '您的姓名',
        'contact.form.email': '電子郵件',
        'contact.form.phone': '聯絡電話',
        'contact.form.subject': '選擇諮詢項目',
        'contact.form.subject.product': '產品諮詢',
        'contact.form.subject.tech': '技術支援',
        'contact.form.subject.quote': '報價需求',
        'contact.form.subject.other': '其他',
        'contact.form.message': '訊息內容',
        'contact.form.submit': '送出訊息',
        'contact.form.sending': '傳送中...',
        'contact.form.success': '訊息已成功送出！我們會盡快與您聯繫。',
        
        // Footer
        'footer.slogan': '引領超音波清洗技術創新',
        'footer.established': '成立於 2009 年',
        'footer.certification': 'ISO 9001 認證',
        'footer.team': '50+ 專業團隊',
        'footer.links': '快速連結',
        'footer.products': '產品系列',
        'footer.products.smart': '智能清洗機',
        'footer.products.precision': '精密清洗系統',
        'footer.products.auto': '自動化清洗線',
        'footer.products.accessories': '清洗配件與耗材',
        'footer.support': '服務支援',
        'footer.support.docs': '技術文件',
        'footer.support.repair': '維修服務',
        'footer.support.training': '教育訓練',
        'footer.support.warranty': '保固條款',
        'footer.copyright': '版權所有',
        'footer.privacy': '隱私權政策',
        'footer.terms': '使用條款',
        'footer.cookies': 'Cookie 設定'
    },
    
    'zh-CN': {
        // 页面标题和品牌
        'page.title': '村齐超声波 - 专业超声波清洗机设备',
        'brand.name': '村齐超声波',
        
        // 导航
        'nav.home': '首页',
        'nav.about': '关于',
        'nav.technology': '技术',
        'nav.products': '产品应用',
        'nav.solutions': '解决方案',
        'nav.contact': '联系',
        
        // Hero 区域
        'hero.badge': '15年专业定制经验',
        'hero.title': '定制化超声波清洗',
        'hero.subtitle': '为您量身打造清洗解决方案',
        'hero.description': '根据您的工件特性、清洗需求与产线配置，设计专属的超声波清洗设备',
        'hero.feature1': '量身定制',
        'hero.feature2': '专业测试',
        'hero.feature3': '完整服务',
        'hero.explore': '探索产品',
        'hero.consult': '免费需求评估',
        'hero.process': '了解设计流程',
        'hero.clients': '合作客户',
        'hero.experience': '年专业经验',
        'hero.cases': '成功案例',
        
        // 设计流程
        'process.label': '设计流程',
        'process.title': '专业定制化设计流程',
        'process.subtitle': '从需求分析到交付使用，我们提供完整的定制化设计服务',
        'process.step1.title': '需求咨询',
        'process.step1.desc': '深入了解您的工件材质、污染类型、清洗要求及产线配置',
        'process.step1.item1': '现场勘查评估',
        'process.step1.item2': '清洗需求分析',
        'process.step1.item3': '技术可行性讨论',
        'process.step2.title': '样品测试',
        'process.step2.desc': '使用实际工件进行清洗测试，确认最佳参数设定',
        'process.step2.item1': '免费样品测试',
        'process.step2.item2': '多种频率验证',
        'process.step2.item3': '清洗效果确认',
        'process.step3.title': '方案设计',
        'process.step3.desc': '根据测试结果设计专属设备，包含机械结构与控制系统',
        'process.step3.item1': '3D设计图面',
        'process.step3.item2': '详细规格说明',
        'process.step3.item3': '报价与交期评估',
        'process.step4.title': '制造组装',
        'process.step4.desc': '采用高品质零组件，严格品质控制下完成设备制造',
        'process.step4.item1': '精密机械加工',
        'process.step4.item2': '电控系统整合',
        'process.step4.item3': '出厂测试验证',
        'process.step5.title': '安装调试',
        'process.step5.desc': '专业工程师到场安装，完成设备调试与人员教育训练',
        'process.step5.item1': '现场安装调试',
        'process.step5.item2': '操作教育训练',
        'process.step5.item3': '验收测试确认',
        'process.cta.title': '准备开始您的定制化项目？',
        'process.cta.desc': '联系我们的工程团队，获得专业的需求评估与解决方案',
        'process.cta.button': '开始需求评估',
        
        // 技术展示
        'tech.label': '技术能力',
        'tech.title': '多元化定制技术方案',
        'tech.subtitle': '针对不同应用需求，我们具备完整的技术解决方案',
        'tech.custom.title': '频率定制化',
        'tech.custom.desc': '根据工件特性选择最适频率',
        'tech.custom.freq1': '20kHz 大功率清洗',
        'tech.custom.freq2': '40kHz 精密清洗',
        'tech.custom.freq3': '80kHz 超精密清洗',
        'tech.custom.freq4': '多频同步作业',
        'tech.solution.title': '清洗液定制化',
        'tech.solution.desc': '配合不同材质设计专用清洗配方',
        'tech.solution.water': '纯水清洗系统',
        'tech.solution.solvent': '有机溶剂系统',
        'tech.solution.alkaline': '碱性清洗系统',
        'tech.solution.acid': '酸性清洗系统',
        'tech.control.title': '控制系统定制化',
        'tech.control.desc': '智能化控制满足自动化需求',
        'tech.control.plc': 'PLC控制系统',
        'tech.control.hmi': '人机界面设计',
        'tech.control.auto': '全自动化整合',
        'tech.control.remote': '远程监控功能',
        'tech.structure.title': '机械结构定制化',
        'tech.structure.desc': '针对产线配置设计专属结构',
        'tech.structure.single': '单槽式设计',
        'tech.structure.multi': '多槽连续式',
        'tech.structure.conveyor': '输送带整合',
        'tech.structure.robot': '机械手臂配合',
        
        // 关于我们
        'about.label': '关于我们',
        'about.title': '创新驱动未来',
        'about.subtitle': '专业超声波清洗设备领导者',
        'about.description': '村齐超声波致力于提供最先进的超声波清洗技术，我们的清洗设备涵盖各个产业领域，从精密电子到医疗器械，为客户提供高效洁净的清洗解决方案。',
        'about.innovation': '创新技术',
        'about.innovation.desc': '持续研发突破性技术',
        'about.quality': '品质保证',
        'about.quality.desc': '国际认证品质管理',
        'about.precision': '精密控制',
        'about.eco': '环保节能',
        'about.efficiency': '高效生产',
        
        // 技术展示
        'tech.label': '核心技术',
        'tech.title': '领先的清洗技术',
        'tech.freq.title': '高频振动清洗',
        'tech.freq.desc': '20kHz-40kHz高频振动，实现微粒级深度清洗',
        'tech.smart.title': '智能清洗系统',
        'tech.smart.desc': 'AI驱动的智能清洗参数优化，自动调节功率与频率',
        'tech.multi.title': '多频段清洗',
        'tech.multi.desc': '多频段同时作用，适应不同材质与污染类型',
        'tech.green.title': '绿色清洗',
        'tech.green.desc': '无化学清洗剂、低能耗的环保清洗技术',
        
        // 产品展示
        'products.label': '产品系列',
        'products.title': '专业设备解决方案',
        'products.smart.title': '智能型超声波清洗机',
        'products.smart.desc': '搭载AI控制系统的新一代清洗设备，适用于各种精密零件清洗',
        'products.precision.title': '精密电子清洗系统',
        'products.precision.desc': '专为电子元件设计的精密清洗方案，有效去除助焊剂、油污等污染',
        'products.auto.title': '全自动化清洗线',
        'products.auto.desc': '整合机器人的自动化清洗解决方案，适合大量生产环境',
        'products.badge.hot': '热销',
        'products.badge.new': '新品',
        'products.tag.smart': '智能控制',
        'products.tag.efficient': '高效清洗',
        'products.tag.eco': '节能环保',
        'products.tag.precision': '精密清洗',
        'products.tag.safe': '无损伤',
        'products.tag.fast': '高效率',
        'products.tag.auto': '全自动',
        'products.tag.capacity': '高产能',
        'products.tag.iot': '智能监控',
        
        // 解决方案
        'solutions.label': '应用领域',
        'solutions.title': '全方位清洗解决方案',
        'solutions.auto.title': '汽车产业',
        'solutions.auto.desc': '引擎零件、车灯、传感器等精密清洗，去除油污、金属屑',
        'solutions.medical.title': '医疗器械',
        'solutions.medical.desc': '医疗器械、手术器具的精密清洗，达到无菌标准',
        'solutions.electronic.title': '电子产业',
        'solutions.electronic.desc': 'PCB电路板、电子元件的助焊剂清洗，提升产品品质',
        'solutions.optical.title': '光学产业',
        'solutions.optical.desc': '镜头、光学元件的精密清洗，保持光学品质',
        'solutions.learn': '深入了解',
        
        // 客户案例
        'cases.label': '客户见证',
        'cases.title': '真实案例 · 可信赖的清洗效果',
        'cases.before': '清洗前',
        'cases.after': '清洗后',
        'cases.dirty': '脏污严重',
        'cases.clean': '洁净如新',
        'cases.oil': '油污残留',
        'cases.complete': '完全清洁',
        'cases.oxidation': '表面氧化',
        'cases.bright': '光亮如新',
        'cases.electronic.title': '精密电子元件清洗',
        'cases.electronic.desc': '某知名电子厂PCB板清洗案例，清洗效率提升300%，良品率达99.8%',
        'cases.auto.title': '汽车零件清洗',
        'cases.auto.desc': '汽车引擎零件深度清洗，有效去除碳积和油污，延长使用寿命',
        'cases.optical.title': '光学镜头清洗',
        'cases.optical.desc': '精密光学镜头清洗，无损伤清除表面污染，保持光学性能',
        'cases.time': '清洗时间',
        'cases.rate': '良品率',
        'cases.cleanliness': '清洁度',
        'cases.damage': '无损率',
        'cases.testimonial1': '"村齐的超声波清洗机帮我们解决了精密零件清洗的难题，效率提升了3倍！"',
        'cases.author1': '张总经理',
        'cases.company1': '精密科技股份有限公司',
        'cases.testimonial2': '"清洗效果令人惊艳，完全没有化学残留，是我们医疗器械清洗的最佳选择。"',
        'cases.author2': '李院长',
        'cases.company2': '北京医学中心',
        
        // CTA 号召行动
        'cta.title': '准备好提升您的清洗效率了吗？',
        'cta.description': '立即联系我们，获得专属的超声波清洗解决方案',
        'cta.contact': '立即咨询',
        'cta.phone': '02-1234-5678',
        
        // 联系我们
        'contact.label': '联系我们',
        'contact.title': '随时为您服务',
        'contact.address': '总部地址',
        'contact.address.value': '台北市信义区信义路五段7号',
        'contact.phone': '联系电话',
        'contact.phone.value': '02-1234-5678',
        'contact.email': '电子邮件',
        'contact.email.value': 'info@cunqi-ultrasonic.com.tw',
        'contact.hours': '营业时间',
        'contact.hours.value': '周一至周五 9:00-18:00',
        'contact.form.title': '在线咨询表单',
        'contact.form.name': '您的姓名',
        'contact.form.email': '电子邮件',
        'contact.form.phone': '联系电话',
        'contact.form.subject': '选择咨询项目',
        'contact.form.subject.product': '产品咨询',
        'contact.form.subject.tech': '技术支持',
        'contact.form.subject.quote': '报价需求',
        'contact.form.subject.other': '其他',
        'contact.form.message': '消息内容',
        'contact.form.submit': '发送消息',
        'contact.form.sending': '发送中...',
        'contact.form.success': '消息已成功发送！我们会尽快与您联系。',
        
        // Footer
        'footer.slogan': '引领超声波清洗技术创新',
        'footer.established': '成立于 2009 年',
        'footer.certification': 'ISO 9001 认证',
        'footer.team': '50+ 专业团队',
        'footer.links': '快速链接',
        'footer.products': '产品系列',
        'footer.products.smart': '智能清洗机',
        'footer.products.precision': '精密清洗系统',
        'footer.products.auto': '自动化清洗线',
        'footer.products.accessories': '清洗配件与耗材',
        'footer.support': '服务支持',
        'footer.support.docs': '技术文档',
        'footer.support.repair': '维修服务',
        'footer.support.training': '教育培训',
        'footer.support.warranty': '保修条款',
        'footer.copyright': '版权所有',
        'footer.privacy': '隐私政策',
        'footer.terms': '使用条款',
        'footer.cookies': 'Cookie 设置'
    },
    
    'en': {
        // Page title and brand
        'page.title': 'CunQi Ultrasonic - Professional Ultrasonic Cleaning Equipment',
        'brand.name': 'CunQi Ultrasonic',
        
        // Navigation
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.technology': 'Technology',
        'nav.products': 'Applications',
        'nav.solutions': 'Solutions',
        'nav.contact': 'Contact',
        
        // Hero Section
        'hero.badge': '15 Years Custom Design Experience',
        'hero.title': 'Custom Ultrasonic Cleaning',
        'hero.subtitle': 'Tailored Cleaning Solutions for You',
        'hero.description': 'Design dedicated ultrasonic cleaning equipment based on your workpiece characteristics, cleaning requirements, and production line configuration',
        'hero.feature1': 'Custom Design',
        'hero.feature2': 'Professional Testing',
        'hero.feature3': 'Complete Service',
        'hero.explore': 'Explore Products',
        'hero.consult': 'Free Requirement Assessment',
        'hero.process': 'Learn Design Process',
        'hero.clients': 'Partner Clients',
        'hero.experience': 'Years of Experience',
        'hero.cases': 'Success Cases',
        
        // Design Process
        'process.label': 'Design Process',
        'process.title': 'Professional Custom Design Process',
        'process.subtitle': 'From requirement analysis to delivery, we provide complete custom design services',
        'process.step1.title': 'Requirement Consultation',
        'process.step1.desc': 'Understand your workpiece materials, contamination types, cleaning requirements, and production line configuration',
        'process.step1.item1': 'On-site survey and assessment',
        'process.step1.item2': 'Cleaning requirement analysis',
        'process.step1.item3': 'Technical feasibility discussion',
        'process.step2.title': 'Sample Testing',
        'process.step2.desc': 'Use actual workpieces for cleaning tests to confirm optimal parameter settings',
        'process.step2.item1': 'Free sample testing',
        'process.step2.item2': 'Multiple frequency verification',
        'process.step2.item3': 'Cleaning effect confirmation',
        'process.step3.title': 'Solution Design',
        'process.step3.desc': 'Design dedicated equipment based on test results, including mechanical structure and control system',
        'process.step3.item1': '3D design drawings',
        'process.step3.item2': 'Detailed specifications',
        'process.step3.item3': 'Quotation and delivery evaluation',
        'process.step4.title': 'Manufacturing Assembly',
        'process.step4.desc': 'Complete equipment manufacturing with high-quality components under strict quality control',
        'process.step4.item1': 'Precision mechanical processing',
        'process.step4.item2': 'Electronic control system integration',
        'process.step4.item3': 'Factory testing verification',
        'process.step5.title': 'Installation Commissioning',
        'process.step5.desc': 'Professional engineers on-site installation, equipment commissioning and personnel training',
        'process.step5.item1': 'On-site installation and commissioning',
        'process.step5.item2': 'Operation training',
        'process.step5.item3': 'Acceptance testing confirmation',
        'process.cta.title': 'Ready to Start Your Custom Project?',
        'process.cta.desc': 'Contact our engineering team for professional requirement assessment and solutions',
        'process.cta.button': 'Start Requirement Assessment',
        
        // Technology
        'tech.label': 'Technical Capabilities',
        'tech.title': 'Diversified Custom Technical Solutions',
        'tech.subtitle': 'We have complete technical solutions for different application requirements',
        'tech.custom.title': 'Frequency Customization',
        'tech.custom.desc': 'Select optimal frequency based on workpiece characteristics',
        'tech.custom.freq1': '20kHz High Power Cleaning',
        'tech.custom.freq2': '40kHz Precision Cleaning',
        'tech.custom.freq3': '80kHz Ultra-precision Cleaning',
        'tech.custom.freq4': 'Multi-frequency Synchronous Operation',
        'tech.solution.title': 'Cleaning Solution Customization',
        'tech.solution.desc': 'Design specialized cleaning formulas for different materials',
        'tech.solution.water': 'Pure Water Cleaning System',
        'tech.solution.solvent': 'Organic Solvent System',
        'tech.solution.alkaline': 'Alkaline Cleaning System',
        'tech.solution.acid': 'Acid Cleaning System',
        'tech.control.title': 'Control System Customization',
        'tech.control.desc': 'Intelligent control meets automation requirements',
        'tech.control.plc': 'PLC Control System',
        'tech.control.hmi': 'HMI Design',
        'tech.control.auto': 'Full Automation Integration',
        'tech.control.remote': 'Remote Monitoring Function',
        'tech.structure.title': 'Mechanical Structure Customization',
        'tech.structure.desc': 'Design dedicated structure for production line configuration',
        'tech.structure.single': 'Single Tank Design',
        'tech.structure.multi': 'Multi-tank Continuous Type',
        'tech.structure.conveyor': 'Conveyor Belt Integration',
        'tech.structure.robot': 'Robotic Arm Coordination',
        
        // About Us
        'about.label': 'About Us',
        'about.title': 'Innovation Drives the Future',
        'about.subtitle': 'Professional Ultrasonic Cleaning Equipment Leader',
        'about.description': 'Cunqi Ultrasonic is committed to providing the most advanced ultrasonic cleaning technology. Our cleaning equipment covers various industrial fields, from precision electronics to medical devices, providing customers with efficient and clean cleaning solutions.',
        'about.innovation': 'Innovation Technology',
        'about.innovation.desc': 'Continuous R&D breakthrough technology',
        'about.quality': 'Quality Assurance',
        'about.quality.desc': 'International certified quality management',
        'about.precision': 'Precision Control',
        'about.eco': 'Eco-Friendly',
        'about.efficiency': 'High Efficiency',
        
        // Technology
        'tech.label': 'Core Technology',
        'tech.title': 'Leading Cleaning Technology',
        'tech.freq.title': 'High-Frequency Vibration Cleaning',
        'tech.freq.desc': '20kHz-40kHz high-frequency vibration for microscopic deep cleaning',
        'tech.smart.title': 'Smart Cleaning System',
        'tech.smart.desc': 'AI-driven intelligent cleaning parameter optimization with automatic power and frequency adjustment',
        'tech.multi.title': 'Multi-Frequency Cleaning',
        'tech.multi.desc': 'Multi-frequency simultaneous operation, adapting to different materials and contamination types',
        'tech.green.title': 'Green Cleaning',
        'tech.green.desc': 'Chemical-free, low-energy eco-friendly cleaning technology',
        
        // Products
        'products.label': 'Product Series',
        'products.title': 'Professional Equipment Solutions',
        'products.smart.title': 'Smart Ultrasonic Cleaner',
        'products.smart.desc': 'Next-generation cleaning equipment with AI control system, suitable for various precision parts cleaning',
        'products.precision.title': 'Precision Electronic Cleaning System',
        'products.precision.desc': 'Precision cleaning solution designed for electronic components, effectively removing flux, oil stains and other contamination',
        'products.auto.title': 'Fully Automated Cleaning Line',
        'products.auto.desc': 'Automated cleaning solution integrated with robots, suitable for mass production environments',
        'products.badge.hot': 'Hot',
        'products.badge.new': 'New',
        'products.tag.smart': 'Smart Control',
        'products.tag.efficient': 'Efficient Cleaning',
        'products.tag.eco': 'Energy Saving',
        'products.tag.precision': 'Precision Cleaning',
        'products.tag.safe': 'No Damage',
        'products.tag.fast': 'High Efficiency',
        'products.tag.auto': 'Full Auto',
        'products.tag.capacity': 'High Capacity',
        'products.tag.iot': 'Smart Monitoring',
        
        // Solutions
        'solutions.label': 'Application Fields',
        'solutions.title': 'Comprehensive Cleaning Solutions',
        'solutions.auto.title': 'Automotive Industry',
        'solutions.auto.desc': 'Precision cleaning of engine parts, lights, sensors, removing oil stains and metal debris',
        'solutions.medical.title': 'Medical Devices',
        'solutions.medical.desc': 'Precision cleaning of medical devices and surgical instruments to sterile standards',
        'solutions.electronic.title': 'Electronics Industry',
        'solutions.electronic.desc': 'Flux cleaning for PCB circuit boards and electronic components, improving product quality',
        'solutions.optical.title': 'Optical Industry',
        'solutions.optical.desc': 'Precision cleaning of lenses and optical components, maintaining optical quality',
        'solutions.learn': 'Learn More',
        
        // Customer Cases
        'cases.label': 'Customer Testimonials',
        'cases.title': 'Real Cases · Reliable Cleaning Results',
        'cases.before': 'Before',
        'cases.after': 'After',
        'cases.dirty': 'Heavily Soiled',
        'cases.clean': 'Like New',
        'cases.oil': 'Oil Residue',
        'cases.complete': 'Completely Clean',
        'cases.oxidation': 'Surface Oxidation',
        'cases.bright': 'Bright as New',
        'cases.electronic.title': 'Precision Electronic Component Cleaning',
        'cases.electronic.desc': 'PCB cleaning case from a famous electronics factory, cleaning efficiency improved by 300%, yield rate reached 99.8%',
        'cases.auto.title': 'Automotive Parts Cleaning',
        'cases.auto.desc': 'Deep cleaning of automotive engine parts, effectively removing carbon deposits and oil stains, extending service life',
        'cases.optical.title': 'Optical Lens Cleaning',
        'cases.optical.desc': 'Precision optical lens cleaning, damage-free removal of surface contamination, maintaining optical performance',
        'cases.time': 'Cleaning Time',
        'cases.rate': 'Yield Rate',
        'cases.cleanliness': 'Cleanliness',
        'cases.damage': 'No Damage Rate',
        'cases.testimonial1': '"Cunqi\'s ultrasonic cleaner helped us solve the problem of precision parts cleaning, efficiency improved by 3 times!"',
        'cases.author1': 'General Manager Zhang',
        'cases.company1': 'Precision Technology Co., Ltd.',
        'cases.testimonial2': '"The cleaning effect is amazing, completely no chemical residue, it is the best choice for our medical device cleaning."',
        'cases.author2': 'Director Lee',
        'cases.company2': 'Taipei Medical Center',
        
        // CTA Call to Action
        'cta.title': 'Ready to Improve Your Cleaning Efficiency?',
        'cta.description': 'Contact us now for your exclusive ultrasonic cleaning solution',
        'cta.contact': 'Consult Now',
        'cta.phone': '02-1234-5678',
        
        // Contact
        'contact.label': 'Contact Us',
        'contact.title': 'Always at Your Service',
        'contact.address': 'Headquarters',
        'contact.address.value': 'No. 7, Sec. 5, Xinyi Rd., Xinyi Dist., Taipei City',
        'contact.phone': 'Phone',
        'contact.phone.value': '02-1234-5678',
        'contact.email': 'Email',
        'contact.email.value': 'info@cunqi-ultrasonic.com.tw',
        'contact.hours': 'Business Hours',
        'contact.hours.value': 'Monday to Friday 9:00-18:00',
        'contact.form.title': 'Online Consultation Form',
        'contact.form.name': 'Your Name',
        'contact.form.email': 'Email',
        'contact.form.phone': 'Phone',
        'contact.form.subject': 'Select Consultation Item',
        'contact.form.subject.product': 'Product Consultation',
        'contact.form.subject.tech': 'Technical Support',
        'contact.form.subject.quote': 'Quote Request',
        'contact.form.subject.other': 'Other',
        'contact.form.message': 'Message Content',
        'contact.form.submit': 'Send Message',
        'contact.form.sending': 'Sending...',
        'contact.form.success': 'Message sent successfully! We will contact you soon.',
        
        // Footer
        'footer.slogan': 'Leading Ultrasonic Cleaning Technology Innovation',
        'footer.established': 'Established in 2009',
        'footer.certification': 'ISO 9001 Certified',
        'footer.team': '50+ Professional Team',
        'footer.links': 'Quick Links',
        'footer.products': 'Product Series',
        'footer.products.smart': 'Smart Cleaners',
        'footer.products.precision': 'Precision Cleaning Systems',
        'footer.products.auto': 'Automated Cleaning Lines',
        'footer.products.accessories': 'Cleaning Accessories & Consumables',
        'footer.support': 'Service Support',
        'footer.support.docs': 'Technical Documents',
        'footer.support.repair': 'Repair Service',
        'footer.support.training': 'Training',
        'footer.support.warranty': 'Warranty Terms',
        'footer.copyright': 'All Rights Reserved',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Use',
        'footer.cookies': 'Cookie Settings'
    },
    
    'vi': {
        // Tiêu đề trang và thương hiệu
        'page.title': 'CunQi Siêu Âm - Thiết Bị Làm Sạch Bằng Sóng Siêu Âm Chuyên Nghiệp',
        'brand.name': 'CunQi Siêu Âm',
        
        // Điều hướng
        'nav.home': 'Trang chủ',
        'nav.about': 'Giới thiệu',
        'nav.technology': 'Công nghệ',
        'nav.products': 'Ứng dụng',
        'nav.solutions': 'Giải pháp',
        'nav.contact': 'Liên hệ',
        
        // Phần Hero
        'hero.badge': '15 Năm Kinh Nghiệm Thiết Kế Tùy Chỉnh',
        'hero.title': 'Làm Sạch Siêu Âm Tùy Chỉnh',
        'hero.subtitle': 'Giải Pháp Làm Sạch Được Thiết Kế Riêng Cho Bạn',
        'hero.description': 'Thiết kế thiết bị làm sạch siêu âm chuyên dụng dựa trên đặc tính chi tiết, yêu cầu làm sạch và cấu hình dây chuyền sản xuất của bạn',
        'hero.feature1': 'Thiết Kế Tùy Chỉnh',
        'hero.feature2': 'Kiểm Thử Chuyên Nghiệp',
        'hero.feature3': 'Dịch Vụ Hoàn Chỉnh',
        'hero.explore': 'Khám phá sản phẩm',
        'hero.consult': 'Đánh Giá Yêu Cầu Miễn Phí',
        'hero.process': 'Tìm Hiểu Quy Trình Thiết Kế',
        'hero.clients': 'Khách hàng đối tác',
        'hero.experience': 'Năm kinh nghiệm',
        'hero.cases': 'Trường hợp thành công',
        
        // Quy trình thiết kế
        'process.label': 'Quy Trình Thiết Kế',
        'process.title': 'Quy Trình Thiết Kế Tùy Chỉnh Chuyên Nghiệp',
        'process.subtitle': 'Từ phân tích yêu cầu đến giao hàng sử dụng, chúng tôi cung cấp dịch vụ thiết kế tùy chỉnh hoàn chỉnh',
        'process.step1.title': 'Tư Vấn Yêu Cầu',
        'process.step1.desc': 'Hiểu sâu về vật liệu chi tiết, loại ô nhiễm, yêu cầu làm sạch và cấu hình dây chuyền sản xuất của bạn',
        'process.step1.item1': 'Khảo sát và đánh giá tại chỗ',
        'process.step1.item2': 'Phân tích yêu cầu làm sạch',
        'process.step1.item3': 'Thảo luận tính khả thi kỹ thuật',
        'process.step2.title': 'Kiểm Thử Mẫu',
        'process.step2.desc': 'Sử dụng chi tiết thực tế để kiểm thử làm sạch, xác nhận cài đặt tham số tối ưu',
        'process.step2.item1': 'Kiểm thử mẫu miễn phí',
        'process.step2.item2': 'Xác minh nhiều tần số',
        'process.step2.item3': 'Xác nhận hiệu quả làm sạch',
        'process.step3.title': 'Thiết Kế Giải Pháp',
        'process.step3.desc': 'Thiết kế thiết bị chuyên dụng dựa trên kết quả kiểm thử, bao gồm cấu trúc cơ khí và hệ thống điều khiển',
        'process.step3.item1': 'Bản vẽ thiết kế 3D',
        'process.step3.item2': 'Mô tả thông số kỹ thuật chi tiết',
        'process.step3.item3': 'Báo giá và đánh giá thời gian giao hàng',
        'process.step4.title': 'Sản Xuất Lắp Ráp',
        'process.step4.desc': 'Sử dụng linh kiện chất lượng cao, hoàn thành sản xuất thiết bị dưới kiểm soát chất lượng nghiêm ngặt',
        'process.step4.item1': 'Gia công cơ khí chính xác',
        'process.step4.item2': 'Tích hợp hệ thống điều khiển điện',
        'process.step4.item3': 'Xác minh kiểm thử xuất xưởng',
        'process.step5.title': 'Lắp Đặt Vận Hành Thử',
        'process.step5.desc': 'Kỹ sư chuyên nghiệp đến tại chỗ lắp đặt, hoàn thành vận hành thử thiết bị và đào tạo nhân viên',
        'process.step5.item1': 'Lắp đặt và vận hành thử tại chỗ',
        'process.step5.item2': 'Đào tạo vận hành',
        'process.step5.item3': 'Xác nhận kiểm thử nghiệm thu',
        'process.cta.title': 'Sẵn Sàng Bắt Đầu Dự Án Tùy Chỉnh Của Bạn?',
        'process.cta.desc': 'Liên hệ với đội ngũ kỹ sư của chúng tôi để có đánh giá yêu cầu chuyên nghiệp và giải pháp',
        'process.cta.button': 'Bắt Đầu Đánh Giá Yêu Cầu',
        
        // Về chúng tôi
        'about.label': 'Về chúng tôi',
        'about.title': 'Đổi mới thúc đẩy tương lai',
        'about.subtitle': 'Nhà lãnh đạo thiết bị làm sạch bằng sóng siêu âm chuyên nghiệp',
        'about.description': 'Cunqi Ultrasonic cam kết cung cấp công nghệ làm sạch bằng sóng siêu âm tiên tiến nhất. Thiết bị làm sạch của chúng tôi bao gồm nhiều lĩnh vực công nghiệp khác nhau, từ điện tử chính xác đến thiết bị y tế, cung cấp cho khách hàng các giải pháp làm sạch hiệu quả và sạch sẽ.',
        'about.innovation': 'Công nghệ đổi mới',
        'about.innovation.desc': 'Nghiên cứu và phát triển liên tục công nghệ đột phá',
        'about.quality': 'Đảm bảo chất lượng',
        'about.quality.desc': 'Quản lý chất lượng được chứng nhận quốc tế',
        'about.precision': 'Kiểm soát chính xác',
        'about.eco': 'Thân thiện môi trường',
        'about.efficiency': 'Hiệu quả cao',
        
        // Công nghệ
        'tech.label': 'Khả Năng Kỹ Thuật',
        'tech.title': 'Giải Pháp Kỹ Thuật Tùy Chỉnh Đa Dạng',
        'tech.subtitle': 'Đáp ứng các yêu cầu ứng dụng khác nhau, chúng tôi có đầy đủ giải pháp kỹ thuật',
        'tech.custom.title': 'Tùy Chỉnh Tần Số',
        'tech.custom.desc': 'Chọn tần số phù hợp nhất dựa trên đặc tính chi tiết',
        'tech.custom.freq1': 'Làm sạch công suất cao 20kHz',
        'tech.custom.freq2': 'Làm sạch chính xác 40kHz',
        'tech.custom.freq3': 'Làm sạch siêu chính xác 80kHz',
        'tech.custom.freq4': 'Hoạt động đồng bộ đa tần số',
        'tech.solution.title': 'Tùy Chỉnh Dung Dịch Làm Sạch',
        'tech.solution.desc': 'Thiết kế công thức làm sạch chuyên dụng phù hợp với các vật liệu khác nhau',
        'tech.solution.water': 'Hệ thống làm sạch nước tinh khiết',
        'tech.solution.solvent': 'Hệ thống dung môi hữu cơ',
        'tech.solution.alkaline': 'Hệ thống làm sạch kiềm',
        'tech.solution.acid': 'Hệ thống làm sạch axit',
        'tech.control.title': 'Tùy Chỉnh Hệ Thống Điều Khiển',
        'tech.control.desc': 'Điều khiển thông minh đáp ứng nhu cầu tự động hóa',
        'tech.control.plc': 'Hệ thống điều khiển PLC',
        'tech.control.hmi': 'Thiết kế giao diện người-máy',
        'tech.control.auto': 'Tích hợp tự động hóa hoàn toàn',
        'tech.control.remote': 'Chức năng giám sát từ xa',
        'tech.structure.title': 'Tùy Chỉnh Cấu Trúc Cơ Khí',
        'tech.structure.desc': 'Thiết kế cấu trúc chuyên dụng cho cấu hình dây chuyền sản xuất',
        'tech.structure.single': 'Thiết kế bồn đơn',
        'tech.structure.multi': 'Loại liên tục đa bồn',
        'tech.structure.conveyor': 'Tích hợp băng tải',
        'tech.structure.robot': 'Phối hợp cánh tay robot',
        
        // Sản phẩm
        'products.label': 'Dòng sản phẩm',
        'products.title': 'Giải pháp thiết bị chuyên nghiệp',
        'products.smart.title': 'Máy làm sạch siêu âm thông minh',
        'products.smart.desc': 'Thiết bị làm sạch thế hệ mới với hệ thống điều khiển AI, phù hợp cho làm sạch các bộ phận chính xác khác nhau',
        'products.precision.title': 'Hệ thống làm sạch điện tử chính xác',
        'products.precision.desc': 'Giải pháp làm sạch chính xác được thiết kế cho các thành phần điện tử, loại bỏ hiệu quả chất trợ hàn, vết dầu và các chất ô nhiễm khác',
        'products.auto.title': 'Dây chuyền làm sạch tự động hoàn toàn',
        'products.auto.desc': 'Giải pháp làm sạch tự động tích hợp robot, phù hợp cho môi trường sản xuất hàng loạt',
        'products.badge.hot': 'Bán chạy',
        'products.badge.new': 'Mới',
        'products.tag.smart': 'Điều khiển thông minh',
        'products.tag.efficient': 'Làm sạch hiệu quả',
        'products.tag.eco': 'Tiết kiệm năng lượng',
        'products.tag.precision': 'Làm sạch chính xác',
        'products.tag.safe': 'Không gây hại',
        'products.tag.fast': 'Hiệu quả cao',
        'products.tag.auto': 'Tự động hoàn toàn',
        'products.tag.capacity': 'Công suất cao',
        'products.tag.iot': 'Giám sát thông minh',
        
        // Giải pháp
        'solutions.label': 'Lĩnh vực ứng dụng',
        'solutions.title': 'Giải pháp làm sạch toàn diện',
        'solutions.auto.title': 'Ngành ô tô',
        'solutions.auto.desc': 'Làm sạch chính xác các bộ phận động cơ, đèn, cảm biến, loại bỏ vết dầu và mảnh kim loại',
        'solutions.medical.title': 'Thiết bị y tế',
        'solutions.medical.desc': 'Làm sạch chính xác thiết bị y tế và dụng cụ phẫu thuật đạt tiêu chuẩn vô trùng',
        'solutions.electronic.title': 'Ngành điện tử',
        'solutions.electronic.desc': 'Làm sạch chất trợ hàn cho bo mạch PCB và linh kiện điện tử, nâng cao chất lượng sản phẩm',
        'solutions.optical.title': 'Ngành quang học',
        'solutions.optical.desc': 'Làm sạch chính xác ống kính và linh kiện quang học, duy trì chất lượng quang học',
        'solutions.learn': 'Tìm hiểu thêm',
        
        // Trường hợp khách hàng
        'cases.label': 'Lời chứng thực của khách hàng',
        'cases.title': 'Trường hợp thực tế · Kết quả làm sạch đáng tin cậy',
        'cases.before': 'Trước khi',
        'cases.after': 'Sau khi',
        'cases.dirty': 'Bẩn nặng',
        'cases.clean': 'Như mới',
        'cases.oil': 'Cặn dầu',
        'cases.complete': 'Hoàn toàn sạch',
        'cases.oxidation': 'Oxy hóa bề mặt',
        'cases.bright': 'Sáng như mới',
        'cases.electronic.title': 'Làm sạch linh kiện điện tử chính xác',
        'cases.electronic.desc': 'Trường hợp làm sạch bo mạch PCB từ một nhà máy điện tử nổi tiếng, hiệu quả làm sạch tăng 300%, tỷ lệ sản phẩm tốt đạt 99.8%',
        'cases.auto.title': 'Làm sạch phụ tùng ô tô',
        'cases.auto.desc': 'Làm sạch sâu các bộ phận động cơ ô tô, loại bỏ hiệu quả cặn carbon và dầu, kéo dài tuổi thọ sử dụng',
        'cases.optical.title': 'Làm sạch ống kính quang học',
        'cases.optical.desc': 'Làm sạch ống kính quang học chính xác, loại bỏ ô nhiễm bề mặt không gây hại, duy trì hiệu suất quang học',
        'cases.time': 'Thời gian làm sạch',
        'cases.rate': 'Tỷ lệ sản phẩm tốt',
        'cases.cleanliness': 'Độ sạch',
        'cases.damage': 'Tỷ lệ không hại',
        'cases.testimonial1': '"Máy làm sạch siêu âm của Cunqi đã giúp chúng tôi giải quyết vấn đề làm sạch các bộ phận chính xác, hiệu quả tăng 3 lần!"',
        'cases.author1': 'Tổng giám đốc Zhang',
        'cases.company1': 'Công ty TNHH Công nghệ Chính xác',
        'cases.testimonial2': '"Hiệu quả làm sạch thật tuyệt vời, hoàn toàn không có cặn hóa chất, đây là lựa chọn tốt nhất cho việc làm sạch thiết bị y tế của chúng tôi."',
        'cases.author2': 'Giám đốc Lee',
        'cases.company2': 'Trung tâm Y tế Taipei',
        
        // CTA Lời kêu gọi hành động
        'cta.title': 'Sẵn sàng cải thiện hiệu quả làm sạch của bạn?',
        'cta.description': 'Liên hệ với chúng tôi ngay để có giải pháp làm sạch siêu âm độc quyền của bạn',
        'cta.contact': 'Tư vấn ngay',
        'cta.phone': '02-1234-5678',
        
        // Liên hệ
        'contact.label': 'Liên hệ với chúng tôi',
        'contact.title': 'Luôn phục vụ bạn',
        'contact.address': 'Trụ sở chính',
        'contact.address.value': 'Số 7, Phần 5, Đường Xinyi, Quận Xinyi, Thành phố Taipei',
        'contact.phone': 'Điện thoại',
        'contact.phone.value': '02-1234-5678',
        'contact.email': 'Email',
        'contact.email.value': 'info@cunqi-ultrasonic.com.tw',
        'contact.hours': 'Giờ làm việc',
        'contact.hours.value': 'Thứ Hai đến Thứ Sáu 9:00-18:00',
        'contact.form.title': 'Biểu mẫu tư vấn trực tuyến',
        'contact.form.name': 'Tên của bạn',
        'contact.form.email': 'Email',
        'contact.form.phone': 'Điện thoại',
        'contact.form.subject': 'Chọn mục tư vấn',
        'contact.form.subject.product': 'Tư vấn sản phẩm',
        'contact.form.subject.tech': 'Hỗ trợ kỹ thuật',
        'contact.form.subject.quote': 'Yêu cầu báo giá',
        'contact.form.subject.other': 'Khác',
        'contact.form.message': 'Nội dung tin nhắn',
        'contact.form.submit': 'Gửi tin nhắn',
        'contact.form.sending': 'Đang gửi...',
        'contact.form.success': 'Tin nhắn đã được gửi thành công! Chúng tôi sẽ liên hệ với bạn sớm nhất.',
        
        // Footer
        'footer.slogan': 'Dẫn đầu đổi mới công nghệ làm sạch bằng sóng siêu âm',
        'footer.established': 'Thành lập năm 2009',
        'footer.certification': 'Chứng nhận ISO 9001',
        'footer.team': 'Đội ngũ chuyên nghiệp 50+',
        'footer.links': 'Liên kết nhanh',
        'footer.products': 'Dòng sản phẩm',
        'footer.products.smart': 'Máy làm sạch thông minh',
        'footer.products.precision': 'Hệ thống làm sạch chính xác',
        'footer.products.auto': 'Dây chuyền làm sạch tự động',
        'footer.products.accessories': 'Phụ kiện và vật tư làm sạch',
        'footer.support': 'Hỗ trợ dịch vụ',
        'footer.support.docs': 'Tài liệu kỹ thuật',
        'footer.support.repair': 'Dịch vụ sửa chữa',
        'footer.support.training': 'Đào tạo',
        'footer.support.warranty': 'Điều khoản bảo hành',
        'footer.copyright': 'Bản quyền thuộc về',
        'footer.privacy': 'Chính sách bảo mật',
        'footer.terms': 'Điều khoản sử dụng',
        'footer.cookies': 'Cài đặt Cookie',
        
        // Sản phẩm
        'products.title': 'Giải pháp thiết bị chuyên nghiệp',
        
        // Giải pháp
        'solutions.auto.title': 'Ngành Ô tô',
        'solutions.auto.desc': 'Làm sạch chính xác các bộ phận động cơ, đèn xe, cảm biến, loại bỏ dầu mỡ và phoi kim loại',
        'solutions.medical.title': 'Thiết bị y tế',
        'solutions.medical.desc': 'Làm sạch chính xác thiết bị y tế và dụng cụ phẫu thuật, đạt tiêu chuẩn vô trùng',
        'solutions.electronic.title': 'Ngành điện tử',
        'solutions.electronic.desc': 'Làm sạch chất trợ hàn trên bảng mạch PCB và linh kiện điện tử, nâng cao chất lượng sản phẩm',
        'solutions.optical.title': 'Ngành quang học',
        'solutions.optical.desc': 'Làm sạch chính xác ống kính và linh kiện quang học, duy trì chất lượng quang học',
        'solutions.learn': 'Tìm hiểu thêm',
        
        // Trường hợp khách hàng
        'cases.label': 'Chứng nhận khách hàng',
        'cases.title': 'Trường hợp thực tế · Hiệu quả làm sạch đáng tin cậy',
        'cases.before': 'Trước khi làm sạch',
        'cases.after': 'Sau khi làm sạch',
        'cases.dirty': 'Bẩn nghiêm trọng',
        'cases.clean': 'Sạch như mới',
        'cases.oil': 'Dầu mỡ còn sót',
        'cases.complete': 'Hoàn toàn sạch sẽ',
        'cases.oxidation': 'Oxy hóa bề mặt',
        'cases.bright': 'Sáng bóng như mới',
        'cases.electronic.title': 'Làm sạch linh kiện điện tử chính xác',
        'cases.electronic.desc': 'Trường hợp làm sạch bảng mạch PCB của nhà máy điện tử nổi tiếng, hiệu quả làm sạch tăng 300%, tỷ lệ sản phẩm tốt đạt 99.8%',
        'cases.auto.title': 'Làm sạch bộ phận ô tô',
        'cases.auto.desc': 'Làm sạch sâu bộ phận động cơ ô tô, loại bỏ hiệu quả carbon và dầu mỡ, kéo dài tuổi thọ sử dụng',
        'cases.optical.title': 'Làm sạch ống kính quang học',
        'cases.optical.desc': 'Làm sạch ống kính quang học chính xác, loại bỏ ô nhiễm bề mặt không gây tổn hại, duy trì hiệu năng quang học',
        'cases.time': 'Thời gian làm sạch',
        'cases.rate': 'Tỷ lệ sản phẩm tốt',
        'cases.cleanliness': 'Độ sạch',
        'cases.damage': 'Tỷ lệ không tổn hại',
        'cases.testimonial1': '"Máy làm sạch siêu âm của Cunqi đã giúp chúng tôi giải quyết vấn đề làm sạch linh kiện chính xác, hiệu quả tăng 3 lần!"',
        'cases.author1': 'Tổng giám đốc Zhang',
        'cases.company1': 'Công ty TNHH Công nghệ Chính xác',
        'cases.testimonial2': '"Hiệu quả làm sạch rất ấn tượng, hoàn toàn không có cặn hóa chất, là lựa chọn tốt nhất cho làm sạch thiết bị y tế của chúng tôi."',
        'cases.author2': 'Viện trưởng Li',
        'cases.company2': 'Trung tâm Y khoa Đài Bắc',
        
        // Liên hệ
        'contact.title': 'Luôn phục vụ bạn',
        
        // Hành động kêu gọi
        'cta.title': 'Sẵn sàng tùy chỉnh giải pháp làm sạch của bạn?',
        'cta.description': 'Liên hệ với chúng tôi ngay để được tư vấn chuyên nghiệp và báo giá miễn phí',
        'cta.contact': 'Liên hệ ngay'
    }
};

// 語言代碼對應的顯示名稱
const languageNames = {
    'zh-TW': '繁中',
    'zh-CN': '简中', 
    'en': 'EN',
    'vi': 'VI'
};

// 導出翻譯數據
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { translations, languageNames };
}